server:
  port: 8070
  tomcat:
    max-threads: 4

spring:
  datasource:
    url: jdbc:postgresql://192.168.100.124:5434/test
    username: jiratech
    password: jiratech
    driverClassName: org.postgresql.Driver
    platform: dev
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

security:
  accessKey: mySecret
  refreshKey: mySecret

